### ISSUE TITLE
Tried this on wandboard quad c1

### ISSUE THREAD

**Issue by spinza** [RobertCNelson/netinstall#40]
I does not start up.
I ran this from an ubuntu 14.04 host.  
http://pastebin.com/t36P9VNi

**Comment by RobertCNelson** [comment]
@spinza and what does the serial port show?

**Comment by spinza** [comment]
I started going through your full build instructions and then I saw the netinstall method in the comments.  I've done the full build before, but prefer to skip full build process.   

The image on the card before I started was working but I wanted to start with a clean image.  My wandboard had been gathering dust and thought I'd try again to get it up and running.  From what I recall the spdif light is a good proxy for whether it's booting.  I recall that the light goes on and then goes off if it's happy (and the existing image did so).  In this case the light stays on.

I don't have serial access?  I've managed without it before.  Do I need it?  I also tried the above with the default debian image.  Same result.

**Comment by spinza** [comment]
The only thing I can think of is that I'm trying it with a different hdmi screen than before.  Might that affect things?

**Comment by spinza** [comment]
Oh and the other thing is that the there is an error in the pastebin with regard to formatting the partition.  I'm at a different location now so can't access the pastebin or the original dump but you can see it.  It complains about the device being in use.  I wasn't sure if this was expected?

**Comment by spinza** [comment]
@RobertCNelson sorry didn't @ you?

**Comment by RobertCNelson** [comment]
No it works fine..  After i made sure to tie the gnd off on the serial cable. (terrible board design)  The hdmi came up with the default video parameters and the install began as normal.

Regards,

**Comment by spinza** [comment]
It was the monitor.
